Tables/urls.py
from django.conf.urls import url
from . import views

app_name = 'Tables'

urlpatterns = [

    url(r'^/index$', views.index),
    url(r'^/jobs$', views.jobs),
    url(r'^/workers$', views.workers),
    url(r'^/storage$', views.storage),
    url(r'^/menu$', views.menu),
    url(r'^/order$', views.order),
    url(r'^/personneldep$', views.personneldep),
    url(r'^/restmenu$', views.restmenu),
    url(r'^/orderqueue$', views.orderqueue)
    #url(r'/^jobs/all/$/', views.jobs),
    #url(r'/^/get/(?P<job_id>\d+)$/', views.job),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^tables', include('Tables.urls')),

]

Tables/models.py
from django.db import models


class Jobs(models.Model):

    idjob = models.AutoField( primary_key=True)
    jobname = models.CharField("Job", max_length=20, null=False)
    jobsalary = models.IntegerField("Salary", null=False)
    jobtodo = models.CharField("What to do", max_length=45, null=False)
    jobrules = models.CharField("Rules", max_length=45, null=False)

    def __str__(self):
        #return 'id=%s; %s; Salary=%s; %s; %s' % (self.idjob, self.jobname, self.jobsalary, self.jobtodo, self.jobrules)
        return  '%s; Salary: %s' %(self.jobname, self.jobsalary)
# class Worker(models.Model)
# Create your models here.
class Workers(models.Model):
    idworker = models.AutoField(primary_key=True)
    workername = models.CharField("Worker",max_length=50, null=False)
    workerage = models.IntegerField("Age",default=20, null=False)
    workergender = models.CharField("Gender",max_length=10, null=False)
    workeraddress = models.CharField("Address",max_length=50, null=False)
    workerpass = models.CharField("Passport",max_length=70, null=False)
    workerjob = models.ForeignKey(Jobs, verbose_name="Job")

    def __str__(self):
        #return 'id=%s; %s; Age=%s; %s; %s; %s; %s' % (self.idworker, self.workername, self.workerage, self.workergender, self.workeraddress, self.workerpass, self.workerjob)
        return '%s; %s'%(self.workername,self.workerjob)

class Storage(models.Model):
    idstorage = models.AutoField(primary_key=True)
    itemname = models.CharField("Product",max_length=50, null=False)
    itemdate = models.DateField("Date of production",null=False)
    itemvalue = models.IntegerField("Value",null=False,default=100)
    itemtouse = models.DateField("Date to use",null=False)
    itemcost = models.IntegerField("Cost",null=False, default=100)
    itemprovider = models.CharField("Provider",null=False, max_length=50)

    def __str__(self):
        #return 'id=%s; %s; %s; Value=%s; %s; Cost=%s; %s' % (self.idstorage, self.itemname, self.itemdate, self.itemvalue, self.itemtouse, self.itemcost, self.itemprovider)
        return '%s; Cost: %s; %s'%(self.itemname, self.itemcost, self.itemprovider)

class Menu(models.Model):
    idmenu = models.AutoField(primary_key=True)
    menuname = models.CharField("Dish",max_length=50, null=False)
    idfirstitem = models.ForeignKey(Storage, related_name="%(app_label)s_%(class)s_firstitemrelated", verbose_name="First product")
    firstitemvalue = models.IntegerField("Value of the first",null=False)
    idsecondtitem = models.ForeignKey(Storage, related_name="%(app_label)s_%(class)s_seconditemrelated", verbose_name="Second product")
    seconditemvalue = models.IntegerField("Value of the second",null=False)
    idthirdtitem = models.ForeignKey(Storage, related_name="%(app_label)s_%(class)s_thirditemrelated", verbose_name="Third product")
    thirditemvalue = models.IntegerField("Value of the third",null=False)
    price = models.IntegerField("Price",null=False)
    cooktime = models.TimeField("Cook time",null=False)

    def __str__(self):
        return '%s; %s; Value1=%s; %s; Value2=%s; %s; Value3=%s; Price=%s; %s' % (self.menuname,self.idfirstitem, self.firstitemvalue, self.idsecondtitem, self.seconditemvalue, self.idthirdtitem, self.thirditemvalue, self.price, self.cooktime)


class Order(models.Model):
    idorder = models.AutoField(primary_key=True)
    orderdatetime = models.DateTimeField("Order date and time",null=False)
    ordername = models.CharField("Customer",max_length=50, null=False)
    orderphone = models.IntegerField("Customer's phone", null=False)
    orderfirstdish = models.ForeignKey(Menu, related_name="%(app_label)s_%(class)s_firstrelated", verbose_name="First dish")
    orderseconddish = models.ForeignKey(Menu, related_name="%(app_label)s_%(class)s_secondrelated", null=True, blank=True, verbose_name="Second dish")
    orderthirddish = models.ForeignKey(Menu, related_name="%(app_label)s_%(class)s_thirdrelated", null=True, blank=True, verbose_name="Third dish")
    orderprice = models.IntegerField("Total price",null=False)
    ordercomplete = models.CharField("Status",max_length=50, null=False)
    orderworker = models.ForeignKey(Workers, null=True, verbose_name="Order waiter")

    def __str__(self):
        return 'id=%s; %s; %s; Phone=%s; %s; %s; %s; Price=%s; %s; %s' % (self.idorder, self.orderdatetime, self.ordername, self.orderphone, self.orderfirstdish, self.orderseconddish,self.orderthirddish, self.orderprice, self.ordercomplete, self.orderworker)

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Main</title>
</head>
<body style="background-image: url(../static/restaurantindex.jpg);background-size: 100%;">
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>


</body>
</html>

templates/jobs.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Tables</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Jobs</H1><HR>
<table width=100%>
    {% for job in jobs %}
        <tr>
            <td>Job: {{job.jobname}}</td>
            <td>Job salary: {{job.jobsalary}}</td>
            <td>What to do: {{job.jobtodo}}</td>
            <td style="border-right:None">Rules: {{job.jobrules}}</td>
        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;">
<form method="POST" style="width:500px;display: inline-block; margin-left: 20px;padding-left: 10px;"> {% csrf_token %}
    {%for field in form%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Add">Add</button> </form>
<form method="GET" style="width:500px;display: inline-block; position: absolute">
    <label>Job</label><br>
    <select name="jobname" required="" style="margin-bottom:8px; padding-bottom:2px">
        {% for jobname in jobnames %}
            <option>{{jobname}}</option>
        {%endfor%}
    </select><br>
    <button type="submit" name="Delete" >Delete</button> </form>
</div>
</body>
</html>

templates/menu.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Tables</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Menu</H1><HR>
<table width=100%>
    {% for dish in menu %}
        <tr>
            <td>Dish: {{dish.menuname}}</td>
            <td>First ingredient: {{dish.idfirstitem}}</td>
            <td>Value 1st: {{dish.firstitemvalue}}</td>
            <td>Second ingredient: {{dish.idsecondtitem}}</td>
            <td>Value 2nd: {{dish.seconditemvalue}}</td>
            <td>Third ingredient: {{dish.idthirdtitem}}</td>
            <td>Value 3rd: {{dish.thirditemvalue}}</td>
            <td>Price: {{dish.price}}</td>
            <td style="border-right:None">Cook time: {{dish.cooktime}}</td>
        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;">
<form method="POST" style="width:500px;display: inline-block; margin-left: 20px;padding-left: 10px;"> {% csrf_token %}
    {%for field in form%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Add">Add</button> </form>
<form method="GET" style="width:500px;display: inline-block; position: absolute">
    <label>Dish</label><br>
    <select name="menuname" required="" style="margin-bottom:8px; padding-bottom:2px">
        {% for dishname in dishnames %}
            <option>{{dishname}}</option>
        {%endfor%}
    </select><br>
    <button type="submit" name="Delete" >Delete</button> </form>
</div>
</body>
</html>

templates/order.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Tables</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Order</H1><HR>
<table width=100%>
    {% for order in orders %}
        <tr>
            <td style="width:80px">Order datetime: {{order.orderdatetime}}</td>
            <td>Customer: {{order.ordername}}</td>
            <td>Customer's phone: {{order.orderphone}}</td>
            <td>First dish: {{order.orderfirstdish}}</td>
            <td>Second dish: {{order.orderseconddish}}</td>
            <td>Third dish: {{order.orderthirddish}}</td>
            <td>Total price: {{order.orderprice}}</td>
            <td>Status: {{order.ordercomplete}}</td>
            <td style="border-right: None; width:90px">Order waiter: {{order.orderworker}}</td>
        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;">
<form method="POST" style="width:500px;display: inline-block; margin-left: 20px;padding-left: 10px;"> {% csrf_token %}
    {%for field in form%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Add">Add</button> </form>
<form method="GET" style="width:500px;display: inline-block; position: absolute">
    {%for field in dform%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Delete" >Delete</button> </form>
</div>
</body>
</html>

templates/orderqueue.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Queries</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Restaurant orders</H1><HR>
<table width=100%>
    {% for order in orders %}
        <tr>
            <td style="width:80px">Order datetime: {{order.orderdatetime}}</td>
            <td>Customer: {{order.ordername}}</td>
            <td>Customer's phone: {{order.orderphone}}</td>
            <td>First dish: {{order.orderfirstdish}}</td>
            <td>Second dish: {{order.orderseconddish}}</td>
            <td>Third dish: {{order.orderthirddish}}</td>
            <td>Total price: {{order.orderprice}}</td>
            <td>Status: {{order.ordercomplete}}</td>
            <td style="border-right: None; width:90px">Order waiter: {{order.orderworker}}</td>

        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;margin-left: 20px;">
    <label>Order status:</label><br>
<form method="GET" style="width:500px;display: inline-block; position: absolute;margin-top: 5px;">
    <select id="id_orderfirstdish" name="orderby" required="">
            <option>all</option>
            <option>accomplished</option>
            <option>unaccomplished</option>

    </select>
    <button type="submit">Show</button> </form>
</div>
</body>
</html>

templates/personneldep.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Queries</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Personnel department</H1><HR>
<table width=100%>
    {% for person in personnel %}
        <tr>
            <td>Worker's name: {{person.workername}}</td>
            <td>Age: {{person.workerage}}</td>
            <td>Gender: {{person.workergender}}</td>
            <td>Address: {{person.workeraddress}}</td>
            <td>Passport: {{person.workerpass}}</td>
            <td style="border-right:None">Job: {{person.workerjob}}</td>

        </tr>
    {% endfor %}
</table>
    <hr></HR>


<div style="width:100%;margin-left: 20px;">
    <label>Sort by:</label><br>
<form method="GET" style="width:500px;display: inline-block; position: absolute;margin-top: 5px;">
    <select id="id_orderworker" name="orderby" required="">
        {% for field in fields %}
        <option value="{{field.name}}">{{field.verbose_name}}</option>

        {%endfor%}
    </select>
    <button type="submit">Sort</button> </form>
</div>
</body>
</html>

templates/restmenu.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Queries</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Restaurant menu</H1><HR>
<table width=100%>
    {% for dish in menu %}
        <tr>
            <td>Dish: {{dish.menuname}}</td>
            <td>First ingredient: {{dish.idfirstitem}}</td>
            <td>Value 1st: {{dish.firstitemvalue}}</td>
            <td>Second ingredient: {{dish.idsecondtitem}}</td>
            <td>Value 2nd: {{dish.seconditemvalue}}</td>
            <td>Third ingredient: {{dish.idthirdtitem}}</td>
            <td>Value 3rd: {{dish.thirditemvalue}}</td>
            <td>Price: {{dish.price}}</td>
            <td style="border-right:None">Cook time: {{dish.cooktime}}</td>

        </tr>
    {% endfor %}
</table>
<hr>


<div style="width:100%;margin-left: 20px;">
    <label>First ingredient provider:</label><br>
<form method="GET" style="width:500px;display: inline-block; position: absolute; margin-top: 5px">
    <select id="id_orderfirstdish" name="orderby" required="">
        <option>all</option>
        {% for field in fields %}
            <option>{{field}}</option>
        {%endfor%}
    </select>
    <button type="submit">Show</button> </form>
</div>
</body>
</html>

templates/storage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Tables</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Storage</H1><HR>
<table width=100%>
    {% for item in storage %}
        <tr>
            <td>Product: {{item.itemname}}</td>
            <td>Date of production: {{item.itemdate}}</td>
            <td>Value: {{item.itemvalue}}</td>
            <td>Date to use: {{item.itemtouse}}</td>
            <td>Cost: {{item.itemcost}}</td>
            <td style="border-right:None">Provider: {{item.itemprovider}}</td>
        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;">
<form method="POST" style="width:500px;display: inline-block; margin-left: 20px;padding-left: 10px;"> {% csrf_token %}
    {%for field in form%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Add">Add</button> </form>
<form method="GET" style="width:500px;display: inline-block; position: absolute">
           <label>Product</label><br>
    <select name="itemname" required="" style="margin-bottom:8px; padding-bottom:2px">
        {% for product in products %}
            <option>{{product}}</option>
        {%endfor%}
    </select>
           <br><label>Provider</label><br>
    <select id="id_orderfirstdish" name="itemprovider" required="" style="margin-bottom:8px; padding-bottom:2px">
        {% for provider in providers %}
            <option>{{provider}}</option>
        {%endfor%}
    </select>
    <br>
    <button type="submit" name="Delete" >Delete</button></form>
</div>
</body>
</html>

templates/workers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Tables</title>
</head>
<body>
<header>
    <div class="nav">
      <ul class="menu">
        <li><a href=#>Queries</a>
        <ul class="submenu">
            <li><a href="personneldep">Personnel department</a></li>
            <li><a href="restmenu">Restaurant menu</a></li>
            <li><a href="orderqueue">Restaurant orders</a></li>
        </ul>
    </li>
    <li><a href=#>Tables</a>
        <ul class="submenu">
            <li><a href="jobs">Jobs</a></li>
            <li><a href="workers">Workers</a></li>
            <li><a href="storage">Storage</a></li>
            <li><a href="menu">Menu</a></li>
            <li><a href="order">Orders</a></li>
        </ul>
    </li>
    <li><a href="index">Main</a></li>
</ul>
    </div>
  </header>
<H1>Workers</H1><HR>
<table width=100%>
    {% for worker in workers %}
        <tr>
            <td>Worker's name: {{worker.workername}}</td>
            <td>Age: {{worker.workerage}}</td>
            <td>Gender: {{worker.workergender}}</td>
            <td>Address: {{worker.workeraddress}}</td>
            <td>Passport: {{worker.workerpass}}</td>
            <td style="border-right:None">Job: {{worker.workerjob}}</td>

        </tr>
    {% endfor %}
</table>
<hr>
<div style="width:100%;">
<form method="POST" style="width:500px;display: inline-block; margin-left: 20px;padding-left: 10px;"> {% csrf_token %}
    {%for field in form%}
        <label class="control-label">{{field.label_tag}}</label>
        <div style="padding-bottom:8px">{{field}}</div>
    {%endfor%}
    <button type="submit" name="Add">Add</button> </form>
<form method="GET" style="width:500px;display: inline-block; position: absolute">
    <label>Worker</label><br>
    <select name="workername" required="" style="margin-bottom:8px; padding-bottom:2px">
        {% for workername in workernames %}
            <option>{{workername}}</option>
        {%endfor%}
    </select><br>
    <button type="submit" name="Delete" >Delete</button> </form>
</div>
</body>
</html>